server.port=8083


spring.application.name=PFA2
spring.datasource.url=jdbc:sqlite:productivity.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# OpenRouter AI Configuration
spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.chat.model=deepseek/deepseek-r1-zero:free